Storage: (in-memory) ITableListPtr implementation
myxo/ssyp_db pull request #16
Opened 2021-07-06 05:45 UTC by siw321

#4

2021-07-06 06:38 UTC, myxo requested changes

2021-07-06 06:38 UTC, myxo commented on lib/src/storage.cpp
> +class TableListInMemory : public ITableList {
Более правильное название будет `InMemoryTableList`. + вынеси in memory реализацию в отдельные .h и .cpp, когда появится другая реализация будет проще, если они будут в отдельных файлах

2021-07-06 06:38 UTC, myxo commented on lib/src/storage.h
> +    virtual bool AddTable(std::string blob) = 0;
Предполагается, что это read only интерфейс, для чтения таблиц из Storage

2021-07-06 06:38 UTC, myxo commented on lib/src/storage.cpp
> +    std::vector<std::string> tables_;
Не совсем так. Предполагается, что datamodel , будет каждый раз запрашивать новый ITableList. То есть tables_ должен быть в Storage, а TableList должен иметь указатель на него.
В дальнейшем, если наша база будет многопоточной, мы должны из разных потоков получать ITableList и он не должен меняться, даже если в этот момент кто-то коммитит новые изменения

2021-07-06 06:38 UTC, myxo commented on lib/src/storage.cpp
> +    size_t table_count_ = 0;
Эту переменную можно заменить на `tables_.size()`

2021-07-06 06:38 UTC, myxo commented on lib/src/storage.h
> +    virtual bool AddTable(std::string blob) = 0;
кстати можно даже сделать существующие методы интерфейса const

2021-07-06 06:38 UTC, myxo commented on test/storage_test.cpp
> +    REQUIRE(tables->GetTable(0) == "key,value");
добавь ещё таблиц и соответсвующие REQUIRE

2021-07-06 18:22 UTC, myxo requested changes

2021-07-06 18:22 UTC, myxo commented on lib/src/storage.h
> +    virtual const std::string GetTable(size_t index) = 0;
Ты сделал, чтобы возвращался константный std::string =) Нужно 
```
virtual std::string GetTable(size_t index) const = 0;
```

2021-07-06 18:22 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +    tables_ = tables;
Лучше использовать синтаксис `InMemoryTableList::InMemoryTableList(...) : tables_(tables) {}`
тогда тут сразу понятно, что инициализация переменной

2021-07-06 18:22 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +bool InMemoryStorage::AddTable(std::string blob) {
Я тут не подумал об одном моменте. Мы же не просто так добавляем таблицы, мы заменяем журнал. Давай переименуем метод в интерфейсе в `AddTableAndClearJournal` и будем очищать журнал.

2021-07-06 18:22 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +bool InMemoryStorage::AddTable(std::string blob) {
+ добавить проверку на это в юнит тест

2021-07-06 18:22 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +    return std::make_shared<InMemoryTableList>(tables);
Ты тут делаешь лишнее копирование (сначала создаешь `tables`, а потом копируешь его в выходящую переменную)

2021-07-06 18:22 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +    return (*tables_)[index];
А если `index` выходит за пределы? В этом случае нужно кидать исключение. В принципе есть даже функция, которая это сразу сделает - at() она проверяет не вышли ли мы за границы
```
tables_->at(index);
```

2021-07-06 20:29 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +bool InMemoryStorage::AddTable(std::string blob) {
Давай даже назовем по-другому `PushJournalToTable`. Смысл в том, что таблицу добавляем именно в конец и при этом стираем журнал. Потом ещё будут функции замены нескольких таблиц на одну

2021-07-07 11:37 UTC, myxo requested changes

2021-07-07 11:37 UTC, myxo commented on lib/src/storage.h
> +    virtual bool PushJournalToTable() = 0;
воу, воу, погоди. А куда входящий аргумент пропал? Конкретный формат таблицы должен задавать Datamodel. Идея как раз в том, что Datamodel знает все о конкретном формате таблиц, журналов etc., а Storage значет все о том как они храняться. А тут ты получается пытаешься задать свой формат журнала (и действительно, ты там просто конкатенируешь строки, чтобы запихнуть в один std::string, а ты подумал насчет того, как потом эту информацию добывать обратно?)

2021-07-07 11:37 UTC, myxo commented on test/storage_test.cpp
> +    storage->WriteToJournal({"key1,value1;", "key2,value2;"});
странный ключ. Ожидалось бы, что во втором случае будет `storage->WriteToJournal({"key2", "value2;"});`

2021-07-07 12:20 UTC, siw321 commented on lib/src/storage.h
> +    virtual bool PushJournalToTable() = 0;
В каком формате будет аргумент std::string blob? Таблица должна записываться в одну строку или в разные? Журнал должен хранить key и value в одной строке или в разных?

2021-07-07 12:34 UTC, myxo commented on lib/src/storage.h
> +    virtual bool PushJournalToTable() = 0;
А тебя это никак не должно волновать. Тебе просто приходит строчка и тебе нужно её сохранить и уметь выдавать

2021-07-07 13:36 UTC, myxo requested changes

2021-07-07 13:36 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +    return (*tables_).at(index);
это можно записать как `tables_->at(index)`

2021-07-07 13:36 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +    }
ты тут пытаешься сделать много много таблиц из одного элемента. Не надо так

2021-07-07 13:36 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +    journal_.resize(0);
`journal_.clean()`

2021-07-07 13:48 UTC, myxo approved these changes
Сделай squash коммитов только

2021-07-07 15:11 UTC, merged