Data model2
myxo/ssyp_db pull request #32
Opened 2021-07-07 08:22 UTC by abramovgeorge

2021-07-07 11:30 UTC, myxo requested changes, later dismissed

2021-07-07 11:30 UTC, myxo commented on lib/src/datamodel.cpp
> +    bool LSMTCommit(Operations ops) {
Почему ты так упорно делаешь эти функции? Я же уже говорил, что их быть не должно. Все это нужно писать в уже существующие.
Сейчас вообще PR странный. Добавлены 3 функции, которые в принципе никак не вызываются, не тестируются...

2021-07-07 13:19 UTC, myxo commented on lib/src/datamodel.cpp
> +    void SerializeOps(Operations ops, IStorage& journal) {
У тебя функция называет SerializeOps, но помимо сериализации она ещё передает данные в storage (который у тебя почему-то называется journal). Нужно либо переименовывать, чтобы отразить что она делает или (и так лучще) пусть она возвращает std::string, а записывать в storage будем там, где эту функцию вызывают

2021-07-07 20:08 UTC, myxo commented
Подтяни изменения из мастера, там CI немного поменялся

2021-07-08 10:22 UTC, ruca905 requested changes

2021-07-08 10:22 UTC, ruca905 commented on test/datamodel_test.cpp
>      ops.push_back(Op{"key", "value", Op::Type::Update});
Нет unit теста, который проверяет случай, когда в commit передают операцию Remove (я написал такой, у меня не работает)

2021-07-08 10:22 UTC, ruca905 commented on lib/src/datamodel.cpp
> +            if (it->substr(7, key.size()) == key) {
Вообще, выглядит страшно, когда начальная позиция второго слова захардкожена цифрой 7, может сделать приватную функцию, которая будет возвращать второе слово?

2021-07-08 10:22 UTC, ruca905 commented on lib/src/datamodel.cpp
> +    std::vector<std::string> journal_;
А точно нужна тут приватная переменная journal_? Кроме, как в GetValue,  она ни где не используется.

2021-07-08 10:22 UTC, ruca905 commented on lib/src/datamodel.cpp
> +    std::vector<std::string> journal_;
И, кстати, из журнала мы читаем, поэтому разумнее его передавать туда по указателю

2021-07-08 10:39 UTC, myxo commented on lib/src/datamodel.cpp
> +    std::vector<std::string> journal_;
Переменная нужна, чтение журнала напрямую из Storage дорогое

2021-07-08 12:09 UTC, ruca905 commented on lib/src/datamodel.cpp
> -        journal_ = storage->GetJournal();
Я ошибся, николай сверху написал, что переменную надо объявлять в конструкторе 1 раз потому что метод GetJournal() тяжёлый

2021-07-08 12:33 UTC, ruca905 approved these changes

2021-07-08 12:44 UTC, merged