Storage: store journal #8
myxo/ssyp_db pull request #35
Opened 2021-07-07 16:14 UTC by siw321

Storage: store journal #8

2021-07-07 19:06 UTC, myxo requested changes

2021-07-07 19:06 UTC, myxo commented on lib/include/settings.h
> +    std::string journal_filename = "journal";
то есть файл называется journal.journal? =) Сделай один префикс имени для обоих случаев. И не делай его по-умолчанию, то есть тут оставь пустым, а в тестах задавай какое-то имя (единственное сделай проверку, что оно не нулевое)

2021-07-07 19:06 UTC, myxo commented on lib/src/storage.cpp
> +            return false;
Выводи в stderr сообщение об ошибке в этом случае. И вообще в случае ошибок

2021-07-07 19:06 UTC, myxo commented on test/storage_test.cpp
> +    REQUIRE(storage->GetJournal()[0] == "key,value,update");
Тебе нужно смоделировать закрытие приложения и считывание журнала заного, в этом случае тест будет примерно таким (и да, в этом случае он не проходит)
```
TEST_CASE("Storage", "[journal]") { 
    DbSettings settings;
    {
        auto storage = CreateStorage(settings);
        REQUIRE(storage->WriteToJournal({"key,value,update"}));
    }
    {
        auto storage = CreateStorage(settings);
        REQUIRE(storage->GetJournal()[0] == "key,value,update");
    }
}
```

2021-07-07 19:06 UTC, myxo commented on test/storage_test.cpp
> +    REQUIRE(storage->WriteToJournal({"key,value,update"}));
А почему такое странная строчка? В принципе в этом нет ничего плохого, но когда ты пишешь код, ты сообщаешь какую-то информацию другим разработчикам. Поэтому просто строчка `key,value` уместнее. Опять же, это не ошибка... Но... Так меньше удивления когда читаешь код.

2021-07-07 19:06 UTC, myxo commented on lib/src/storage.h
> +#include <fstream>
хедеры нужно подключать там, где они используются. Конкретно этот используется именно в storage.cpp. Оно, конечно, компилируется, но компиляция несколько замедляется. В нашем проекте мы этого наврятли заметим, но в проектах на 1000+ файлов это может быть существенным

2021-07-07 19:06 UTC, myxo commented on lib/src/storage.cpp
> +        return storage;
не нужно создавать лишнюю переменную, просто 
```
return std::make_shared<Storage>(settings.journal_filename, settings.tablelist_filename);
```
выше то же самое

2021-07-07 19:06 UTC, myxo commented on lib/src/storage.cpp
> +            return {"null"};
лучше кидать исключение в таком случае, а то вдруг такую же строчку запихнут в нормальном случае.
```
throw std::runtime_error(std::string("Cannot open journal file: ") + journal_filename_);
```

2021-07-07 19:06 UTC, myxo commented on lib/src/storage.cpp
> +        file.open(journal_filename_);
Можно, кстати, просто `std::ifstream file(journal_filename_)`

2021-07-07 20:03 UTC, myxo commented on test/storage_test.cpp
> +    REQUIRE(storage->GetJournal()[0] == "key,value,update");
+ перед тестом и после теста нужно удалять файл в который ты пишешь. Иначе при следующем запуске теста ты не получишь нужный результат

2021-07-07 20:05 UTC, myxo commented on test/storage_test.cpp
> +    REQUIRE(storage->GetJournal()[0] == "key,value,update");
И вот ещё не проходящий тест, нужно добавить (как отдельный TEST_CASE, конечно)
```
TEST_CASE("Storage", "[journal]") { 
    DbSettings settings;
    {
        auto storage = CreateStorage(settings);
        REQUIRE(storage->WriteToJournal({"key\nvalue"}));
    }
    {
        auto storage = CreateStorage(settings);
        REQUIRE(storage->GetJournal()[0] == "key\nvalue");
    }
}
```

2021-07-07 20:06 UTC, myxo commented on test/storage_test.cpp
> +    REQUIRE(storage->GetJournal()[0] == "key,value,update");
Ещё нужно проверить, что размер GetJournal() правильный (что количество операций осталось таким же)

2021-07-08 08:42 UTC, ruca905 commented on lib/src/storage.cpp
>          IStoragePtr storage = std::make_shared<InMemoryStorage>();
Тут тоже можно без дополнительной переменной `IStoragePtr storage`, `std::make_shared` сразу в `return`

2021-07-08 08:54 UTC, ruca905 commented on test/storage_test.cpp
> +        REQUIRE(storage->WriteToJournal({"key1\nvalue1"}));
Хм, `key1,value1` же как то логичнее. Зачем `\n`?

2021-07-08 09:32 UTC, ruca905 approved these changes

2021-07-08 10:36 UTC, myxo approved these changes

2021-07-08 10:37 UTC, merged