Spaces in keys or values and no_value bugfix
myxo/ssyp_db pull request #40
Opened 2021-07-08 14:45 UTC by abramovgeorge

2021-07-08 15:53 UTC, ruca905 requested changes

2021-07-08 15:53 UTC, ruca905 commented on test/datamodel_test.cpp
Если здесь вставить тест:
```
datamodel->GetValue("key", value)
REQUIRE(value == "");
```
то он не пройдёт

2021-07-08 16:08 UTC, myxo commented on test/datamodel_test.cpp
Да нет, конкретно в этом кейсе все нормально должно быть

2021-07-08 16:11 UTC, myxo commented on test/datamodel_test.cpp
> +    ops.push_back(Op{"key space test", "value with spaces", Op::Type::Update});
Вообще, несколько общих слов. Не надо все пихать в один тест кейс. Тесты они как раз нужны для того, чтобы их написать и не менять в дальнейшем (если, конечно, тест правильный и у нас не изменился интерфейс)

При этом тест кейсы должны проверять что-то одно.  Например 
1. set / get
2. set + remove / get
3. set / get какой-то несуществующий ключ
4. Граничные значения (типа ключей с пробелами)

Не экономь на строчках кода

2021-07-09 02:41 UTC, ruca905 approved these changes

2021-07-09 04:03 UTC, merged