Datamodel: create table from journal
myxo/ssyp_db pull request #43
Opened 2021-07-09 13:52 UTC by abramovgeorge

2021-07-09 16:34 UTC, ruca905 requested changes

2021-07-09 16:34 UTC, yarkivaev commented on lib/include/settings.h
> +    int journal_limit;
По идее, конечно, size_t, но я думаю и так пойдёт

2021-07-09 16:34 UTC, ruca905 commented on lib/src/datamodel.cpp
> +            storage_->PushJournalToTable(TableToString(GenerateTable()));
Во, это красиво

2021-07-09 16:34 UTC, ruca905 commented on lib/src/datamodel.cpp
> +            s_key = it->substr(it->find(' ') + 1, key_length_int);
Вообще, объектно-ориентированный подход предполагает, что детали реализации чего-либо скрываются. Так, например, здесь, вместо того, чтобы описывать каждый раз механизм вытаскивания `key` или `value` из строки операции, лучше создать функции `getKeyFromOp(string op)` и `getValueFromOp(string op)`. Это позволяет делать красивый, читаемый, поддерживаемый код(как сверху, например)

2021-07-09 16:34 UTC, ruca905 commented on lib/src/datamodel.cpp
> +                    s_value = it->substr(it->find(' ') + key_length_int + 2,
Вот, эту штуку ещё можно скрыть в функцию

2021-07-09 16:34 UTC, ruca905 commented on lib/src/datamodel.cpp
> +                    s_value = it->substr(it->find(' ') + key_length_int + 2,
И дальше, там, ещё есть, поищи

2021-07-09 16:34 UTC, ruca905 commented on lib/src/datamodel.cpp
>          return false;
А `GetValue` то, получается, уже не работает, когда данные уходят в таблицы. Но это уже или другой issue, или `GetValue` и должен брать только из журнала @myxo?

2021-07-09 16:34 UTC, ruca905 commented on test/datamodel_test.cpp
>      ops.push_back(Op{"key", "value", Op::Type::Update});
Ну, вот про то, что я сверху говорил, добавить несколько операций после этой строки, и тест уже не пройдёт

2021-07-10 22:48 UTC, myxo requested changes

2021-07-10 22:48 UTC, myxo commented on lib/include/settings.h
> +    int journal_limit;
Поставь значение по-умолчанию, а то что если забудут? 100 кажется адекватным

2021-07-10 22:48 UTC, myxo commented on lib/src/datamodel.cpp
> +            key_length = it->substr(it->find_last_of(' ') + 1);
Слушай, вот чего я не могу понять, почему ты операции в виде строк хранишь? В виде строк они обязаны быть в Storage, потому-что он их в файл записывает. Тут journal_ вполне может быть `std::vector<Op>`.  Тогда часть кода упросититься и в целом станет работать оптимальнее.

2021-07-10 22:48 UTC, myxo commented on lib/src/datamodel.cpp
> +        std::vector<std::string> banned_keys;
Если хочется делать такую переменную, то лучше делать её `std::set<std::string>`, set - контейнер основанный на бинарном дереве, поиск в нем будет за логарифм (а если std::unordered_set, то вообще за константу).

Но тут он вообще не нужен. Если у нас есть операция удаления значения, то она обязана остаться. У нас ведь могут быть ещё таблицы и если мы потеряем информацию, что значение удалили, то чтение будет багованое.

2021-07-10 22:48 UTC, myxo commented on lib/src/datamodel.cpp
> +                                         it->find_last_of(' ') - it->find(' ') -
ох... Ты ведь понимаешь, что каждый такой `find(' ')` - это линейная операция. А ты их повторяешь несколько раз. Нужно сохранять такие расчеты в переменные. В GetValue такая же ерундистика, кстати.

2021-07-10 22:48 UTC, myxo commented on lib/src/datamodel.cpp
> +        std::string s = "";
Можно просто
```
std::string s;
```
Он нормально проинициализируется пустой строчкой

2021-07-10 22:48 UTC, myxo commented on lib/src/datamodel.cpp
> +                 std::to_string(it->second.size()) + " " + it->second + " ";
А зачем ты вообще делаешь пробелы после ключа и значений? Кажется, что если у нас есть их размеры, то это ни к чему

2021-07-10 22:48 UTC, myxo commented on lib/src/datamodel.cpp
> +        int key_length, value_length;
Старайся объявлять переменные там, где они нужны. Эти, например, нужны внутри цикла, а не вне его

2021-07-10 22:48 UTC, myxo commented on lib/src/datamodel.cpp
> +                         value_length);
`substr` каждый вызов делает новую строчку, то есть у тебя идет почти полное копирование тут. Есть 2 выхода
1. Тащить индекс элемента, начиная с которого ты сейчас работаешь
2. Обернуть s в std::string_view. Это специальный невладеющая обертка на строками. В ней операция типа substr уже довольно легкая

2021-07-10 22:49 UTC, myxo commented on lib/src/datamodel.cpp
>          return false;
GetValue должен искать и по таблицам тоже. И другого пункта на эту тему нет, нужно тут делать

2021-07-11 13:24 UTC, ruca905 requested changes

2021-07-11 13:24 UTC, yarkivaev commented on lib/src/datamodel.cpp
> +    Operations StringToOps(std::vector<std::string> s) {
Он же по идее private должен быть, это не является функциональностью, которую предоставляет datamodel

2021-07-11 13:24 UTC, ruca905 commented on lib/src/datamodel.cpp
> +            value = it->substr(first_space + key_length + 2,
И всё-же, любой участок кода, функциональность которого можно описать(например, вот этот участок вытаскивает key из операции), и\или, в котором содержится какая-то магия, понять которую сходу тяжело, желательно выносить в отдельные функции. Так код становится более понятным, а значит с ним удобнее работать и.т.д.

2021-07-11 13:24 UTC, ruca905 commented on lib/src/datamodel.cpp
> +            value = it->substr(first_space + key_length + 2,
Кстати, если там проблема с тем, что переменные `first_space` и `last_space` нужны для нахождения и `key`, и `type`, и `value`, можно сделать 1 функцию, которая будет парсить операцию в виде строки ~~и будет возвращать tuple~~ и будет возвращать `Op`

2021-07-11 13:24 UTC, ruca905 commented on lib/src/datamodel.cpp
> +        if (journal_.size() + ops.size() > journal_limit_) {
Хм, а зачем. Сильно, на производительность это не влияет вроде, просто будет больше таблиц в памяти, чем в предыдущем варианте, зато журналы будут реже переполненны. В общем, я сам не знаю, хорошо это или плохо @myxo?

2021-07-11 13:24 UTC, ruca905 commented on test/datamodel_test.cpp
> +    datamodel->Commit({});
Ну, и тут бы проверить, что журнал, действительно, пуст

2021-07-11 17:23 UTC, myxo requested changes

2021-07-11 17:23 UTC, myxo commented on lib/src/datamodel.cpp
> +        if (journal_.size() + ops.size() > journal_limit_) {
В целом нормально. Это чтобы журнал не пересе лимита с текущим коммитом

2021-07-11 17:23 UTC, myxo commented on lib/src/datamodel.cpp
> +    Op StringToOp(std::string s) {
Давайте начинать следить за копированиями. Принимая по std::string ты делаешь копию строчки. Если принимать по `std::string const&`, копии не будет

2021-07-11 17:23 UTC, myxo commented on lib/src/datamodel.cpp
> +                    banned_keys.insert(it->key);
Ещё раз. Информация о том, что ключ удалили должна остаться в таблице. Этот ключ же может храниться в предыдущих таблицах. Сделай юнит тест на это дело

2021-07-12 02:43 UTC, ruca905 requested changes

2021-07-12 02:43 UTC, ruca905 commented on lib/src/datamodel.cpp
>      std::map<std::string, std::string> GenerateTable() {
Это же по идее приватная функция

2021-07-12 02:43 UTC, ruca905 commented on lib/src/datamodel.cpp
>      std::map<std::string, std::string> GenerateTable() {
И `TableToString тоже`

2021-07-12 03:59 UTC, ruca905 approved these changes

2021-07-12 08:37 UTC, myxo approved these changes

2021-07-12 08:37 UTC, myxo commented on test/datamodel_test.cpp
> +    settings.journal_limit = 10;
Вот это больше не нужно, надо откатить.  Но можно уже в след. PR

2021-07-12 09:09 UTC, merged