storage: merging tables(in memory)
myxo/ssyp_db pull request #54
Opened 2021-07-13 11:15 UTC by siw321

2021-07-13 14:06 UTC, ruca905 commented on test/storage_test.cpp
> +    REQUIRE(tables->GetTable(2) == "key1,value1;key2,value2");
Хм, по идее тут ещё надо проверить количество таблиц. Вместо 2 должна быть 1

2021-07-13 14:10 UTC, myxo requested changes

2021-07-13 14:10 UTC, myxo commented on test/storage_test.cpp
> +    REQUIRE(tables->GetTable(2) == "key1,value1;key2,value2");
Мне кажется ты не совсем понял задачу. Смотри должно быть так.
```
storage->MergeTable({0, 1},
                      tables->GetTable(0) + ";" + tables->GetTable(1));
auto new_tables = storage->GetTableList();

REQUIRE(tables->TableCount() == 2);
REQUIRE(tables->GetTable(0) == "key1,value1");
REQUIRE(tables->GetTable(1) == "key2,value2");

REQUIRE(new_tables ->TableCount() == 1);
REQUIRE(new_tables ->GetTable(0) == "key1,value1;key2,value2");
```
То есть те, кто получил таблицы до мерджа, должны по идти по старым таблицам. Те, кто получил после мерджа, должны идти по новым

2021-07-13 14:10 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +            merged_tables_indexes_.insert({it, table_list_->size()});
Кстати, насколько я помню, insert как раз вставляет элемент только тогда, когда его ещё нет в мапе

2021-07-13 20:34 UTC, myxo requested changes

2021-07-13 20:34 UTC, myxo commented on lib/src/in_memory_storage.cpp
> +    table_list_.push_back(std::make_shared<std::string>(result_table));
Да, это уже ближе к делу. Единственное что, попробуй запустить такой тест (ну точнее это не тест, а просто кусок кода). По идее он должен нормально работать, но у меня довольно быстро падает. Попробуй понять почему
```
TEST_CASE("InMemoryStorage multithreaded", "[]") {
    DbSettings settings;
    settings.in_memory = true;
    auto storage = CreateStorage(settings);

    std::thread t{[&]{
        while (true) {
            auto tables = storage->GetTableList();
            for (int i = tables->TableCount() - 1; i >= 0; i--) {
                std::string t = tables->GetTable(i);
                // and here Datamodel try to read value
            }
        }
    }};

    while (true) {
        storage->WriteToJournal({"key1,value1"});
        storage->PushJournalToTable(storage->GetJournal()[0]);

        storage->WriteToJournal({"key2,value2"});
        storage->PushJournalToTable(storage->GetJournal()[0]);

        auto tables = storage->GetTableList();
        storage->MergeTable({0, 1},
            tables->GetTable(0) + ";" + tables->GetTable(1));
    }
}
```

2021-07-14 07:03 UTC, myxo approved these changes

2021-07-14 07:03 UTC, merged