storage: merging tables(in file)
myxo/ssyp_db pull request #61
Opened 2021-07-14 11:19 UTC by siw321

Storage: merge table #50

2021-07-14 20:15 UTC, myxo requested changes

2021-07-14 20:15 UTC, myxo commented on lib/src/storage.cpp
> +    std::shared_ptr<std::string> tablelist_filename_;
А он с чего shared_ptr стал?

2021-07-14 20:15 UTC, myxo commented on lib/src/storage.cpp
> +        table_addresses_ = {};
Это лишнее. std::vector и так по-умолчанию конструируется

2021-07-14 20:15 UTC, myxo commented on lib/src/storage.cpp
> +        std::remove(journal_filename_.c_str());
А файл журнала-то за что?

2021-07-14 20:15 UTC, myxo commented on lib/src/storage.cpp
> +        }
Тебе нужно объяснить что тут происходит, потому-что я так и не понял =(

2021-07-14 20:15 UTC, myxo commented on test/storage_test.cpp
> +        REQUIRE(tables->GetTable(0) == "key1,value1;key2value2");
Нужно больше тестов. Я не верю, что это окучивает все варианты. Как минимум нету случая, когда мы несколько раз проводим операцию MergeTable.

ps. И не пихай все в один TEST_CASE, делай разные на разные тесты

2021-07-14 20:16 UTC, myxo commented on lib/src/storage.cpp
> +                tables_file.read((char*)&merged_table, sizeof(int32_t));
Кстати, а почему int32_t? Так ты сможешь работать только с базой величиной 2гб, мы целимся на побольше

2021-07-15 06:34 UTC, siw321 commented on lib/src/storage.cpp
> +        }
table_addresses_ хранит адреса таблиц в файле, которые не "удалили". В MergeTable() удаляются адреса "удаленных" таблиц.

2021-07-15 07:51 UTC, myxo approved these changes
Ну ладно. Если честно у меня есть ощущение, что мы тут не все случаи проверили и где-то ещё может быть бага. Но сразу понять не получилось. Давай будем мерджить, а потом если найдем ошибку, заведем отдельный тикет

2021-07-15 07:52 UTC, merged